<div class="container">
    <div class="login">
        <h2>Sistema Foda-se</h2>
        <form action="autenticar" method="POST">
            <label for="email"><b>Email</b></label>
            <input type="email" placeholder="Seu email" name="email" required>

            <label for="senha"><b>Senha</b></label>
            <input type="password" placeholder="Sua senha" name="senha" required>

            <input type="submit" name="btn-cad" value="Entrar">
            
            <?php if($this->view->login == 'erro'): ?>
                <p class="erro">Email ou senha inválidos</p>
            <?php endif; ?>
        </form>
            <div class="btn">
                <a href="/inscreverse">Criar conta</a>
            </div>
    </div>
</div>