
<div class="container">
    <div class="login">
        <h2>Criar Conta</h2>
        <form action="/registrar" method="POST">

            <label for="nome"><b>Nome</b></label>
            <input type="text" placeholder="Seu email" name="nome" required>

            <label for="email"><b>Email</b></label>
            <input type="email" placeholder="Seu email" name="email" required>

            <label for="senha"><b>Senha</b></label>
            <input type="password" placeholder="Sua senha" name="senha" required>

            <input type="submit" name="btn-cad" value="Cadastrar">
    
    <?php if($this->view->erroCadastro): ?>
        <p class="erro">Erro ao realizar cadastro, verifique os campos e tente novamente</p>
    <?php endif; ?>
</form>